const PREDEFINED_SCHEMAS = [
  {
    id: 'academic_transcript',
    label: 'Academic Transcript',
    description: 'Student profile, term summaries, per-course records, and transcript-wide summary metrics.',
    recommended_for: ['university transcript', 'college transcript', 'grade report'],
    spec: {
      document_type: 'Academic Transcript',
      title: 'Academic Transcript Extraction',
      detail_level: 'standard',
      summary: 'Extract student identity, term-level academic history, and course records from a transcript.',
      fields: [
        {
          id: 'student_name',
          label: 'Student Name',
          type: 'text',
          required: true,
          description: 'Full student name shown on the transcript.',
          extraction_hint: 'Look for the student name in the document header or metadata block.',
        },
        {
          id: 'student_id',
          label: 'Student ID',
          type: 'text',
          required: false,
          description: 'School-issued student identifier.',
          extraction_hint: 'Look for a student ID label near the header.',
        },
        {
          id: 'institution',
          label: 'Institution',
          type: 'text',
          required: true,
          description: 'Name of the institution issuing the transcript.',
          extraction_hint: 'Use the university or institution name in the header.',
        },
        {
          id: 'institution_id',
          label: 'Institution ID',
          type: 'text',
          required: false,
          description: 'Institution code or ID shown on the transcript.',
          extraction_hint: 'Look for institution code or institution ID near the header.',
        },
        {
          id: 'degree',
          label: 'Degree',
          type: 'text',
          required: false,
          description: 'Degree program shown on the transcript.',
          extraction_hint: 'Capture the degree program exactly as written.',
        },
        {
          id: 'majors',
          label: 'Declared Majors',
          type: 'list',
          required: false,
          description: 'All majors declared anywhere in the transcript.',
          extraction_hint: 'Combine all distinct majors stated in the transcript.',
        },
        {
          id: 'print_date',
          label: 'Print Date',
          type: 'date',
          required: false,
          description: 'Transcript print or issue date.',
          extraction_hint: 'Look for print date or issue date in the header.',
        },
        {
          id: 'cumulative_gpa',
          label: 'Cumulative GPA',
          type: 'number',
          required: false,
          description: 'Latest cumulative GPA stated on the transcript.',
          extraction_hint: 'Use the final cumulative GPA shown in the transcript.',
        },
        {
          id: 'completed_credits',
          label: 'Completed Credits',
          type: 'number',
          required: false,
          description: 'Total completed credit hours excluding in-progress courses when possible.',
          extraction_hint: 'Use the latest completed or earned credit total with real grades.',
        },
      ],
      groups: [
        {
          id: 'terms',
          label: 'Terms',
          repeat: true,
          description: 'Per-term academic summaries.',
          key_hint: 'Term name such as Fall 2025',
          fields: [
            {
              id: 'term',
              label: 'Term',
              type: 'text',
              required: true,
              description: 'Academic term name.',
              extraction_hint: 'Use the visible term heading.',
            },
            {
              id: 'school',
              label: 'School',
              type: 'text',
              required: false,
              description: 'School or division for the term.',
              extraction_hint: 'Capture the school shown under the term header.',
            },
            {
              id: 'majors_at_time',
              label: 'Majors At Time',
              type: 'list',
              required: false,
              description: 'Majors declared during the term.',
              extraction_hint: 'List the majors shown for that term.',
            },
            {
              id: 'term_gpa',
              label: 'Term GPA',
              type: 'number',
              required: false,
              description: 'GPA for the term.',
              extraction_hint: 'Use the term or current GPA for the term block.',
            },
            {
              id: 'term_hours',
              label: 'Term Hours',
              type: 'number',
              required: false,
              description: 'Hours completed in the term.',
              extraction_hint: 'Use the term hours or AHRS total shown for the term.',
            },
            {
              id: 'cumulative_gpa',
              label: 'Cumulative GPA',
              type: 'number',
              required: false,
              description: 'Cumulative GPA after the term.',
              extraction_hint: 'Use the cumulative GPA row for the term.',
            },
            {
              id: 'cumulative_hours',
              label: 'Cumulative Hours',
              type: 'number',
              required: false,
              description: 'Cumulative hours after the term.',
              extraction_hint: 'Use the cumulative AHRS or cumulative hours row.',
            },
            {
              id: 'honors',
              label: 'Honors',
              type: 'text',
              required: false,
              description: 'Term-level honors or academic distinctions.',
              extraction_hint: 'Capture any honor line tied to the term.',
            },
          ],
          subgroups: [
            {
              id: 'courses',
              label: 'Courses',
              repeat: true,
              description: 'Courses recorded for the term.',
              key_hint: 'Course code',
              fields: [
                {
                  id: 'code',
                  label: 'Course Code',
                  type: 'text',
                  required: true,
                  description: 'Course code or catalog identifier.',
                  extraction_hint: 'Use the course code exactly as printed.',
                },
                {
                  id: 'name',
                  label: 'Course Name',
                  type: 'text',
                  required: true,
                  description: 'Course title.',
                  extraction_hint: 'Capture the course title associated with the code.',
                },
                {
                  id: 'credits',
                  label: 'Credits',
                  type: 'number',
                  required: false,
                  description: 'Credit value for the course.',
                  extraction_hint: 'Use the course credit hours.',
                },
                {
                  id: 'grade',
                  label: 'Grade',
                  type: 'text',
                  required: false,
                  description: 'Grade or in-progress marker.',
                  extraction_hint: 'Capture the visible grade exactly as shown.',
                },
                {
                  id: 'in_progress',
                  label: 'In Progress',
                  type: 'boolean',
                  required: false,
                  description: 'Whether the course is still in progress.',
                  extraction_hint: 'Mark true when the grade indicates in-progress or pending status.',
                },
              ],
            },
          ],
        },
      ],
      warnings: [],
    },
  },
  {
    id: 'invoice',
    label: 'Invoice',
    description: 'Invoice metadata, parties, money totals, due dates, and line items.',
    recommended_for: ['invoice', 'bill', 'accounts payable', 'vendor invoice'],
    spec: {
      document_type: 'Invoice',
      title: 'Invoice Extraction',
      detail_level: 'standard',
      summary: 'Extract billing metadata, parties, totals, and invoice line items.',
      fields: [
        { id: 'invoice_number', label: 'Invoice Number', type: 'text', required: true, description: 'Primary invoice identifier.', extraction_hint: 'Use the invoice number or reference number.' },
        { id: 'invoice_date', label: 'Invoice Date', type: 'date', required: false, description: 'Date the invoice was issued.', extraction_hint: 'Look for invoice date or issue date.' },
        { id: 'due_date', label: 'Due Date', type: 'date', required: false, description: 'Payment due date.', extraction_hint: 'Look for due date or payment due.' },
        { id: 'vendor_name', label: 'Vendor Name', type: 'text', required: false, description: 'Seller or issuing company.', extraction_hint: 'Use the company sending the invoice.' },
        { id: 'customer_name', label: 'Customer Name', type: 'text', required: false, description: 'Billed customer or recipient.', extraction_hint: 'Use the billed-to or customer name.' },
        { id: 'subtotal', label: 'Subtotal', type: 'currency', required: false, description: 'Subtotal before taxes or fees.', extraction_hint: 'Capture the subtotal if stated.' },
        { id: 'tax', label: 'Tax', type: 'currency', required: false, description: 'Total tax amount.', extraction_hint: 'Use the total tax value if present.' },
        { id: 'total_amount', label: 'Total Amount', type: 'currency', required: true, description: 'Final amount due.', extraction_hint: 'Use the invoice total or balance due.' },
        { id: 'currency', label: 'Currency', type: 'text', required: false, description: 'Currency code or symbol context.', extraction_hint: 'Infer from symbols or explicit currency labels if present.' },
      ],
      groups: [
        {
          id: 'line_items',
          label: 'Line Items',
          repeat: true,
          description: 'Individual invoice charges or items.',
          key_hint: 'Item description',
          fields: [
            { id: 'description', label: 'Description', type: 'text', required: true, description: 'Description of the billed item.', extraction_hint: 'Use the line item description.' },
            { id: 'quantity', label: 'Quantity', type: 'number', required: false, description: 'Billed quantity.', extraction_hint: 'Use the quantity column if present.' },
            { id: 'unit_price', label: 'Unit Price', type: 'currency', required: false, description: 'Price per unit.', extraction_hint: 'Use the rate or unit price value.' },
            { id: 'amount', label: 'Amount', type: 'currency', required: false, description: 'Extended amount for the line item.', extraction_hint: 'Use the line total or amount column.' },
          ],
          subgroups: [],
        },
      ],
      warnings: [],
    },
  },
  {
    id: 'resume',
    label: 'Resume / CV',
    description: 'Candidate profile, contact details, experience, education, projects, and skills.',
    recommended_for: ['resume', 'cv', 'curriculum vitae'],
    spec: {
      document_type: 'Resume',
      title: 'Resume Extraction',
      detail_level: 'standard',
      summary: 'Extract candidate identity, contact info, experience, education, projects, and skills.',
      fields: [
        { id: 'full_name', label: 'Full Name', type: 'text', required: true, description: 'Candidate full name.', extraction_hint: 'Use the main name header.' },
        { id: 'email', label: 'Email', type: 'email', required: false, description: 'Primary email address.', extraction_hint: 'Capture the main contact email.' },
        { id: 'phone', label: 'Phone', type: 'phone', required: false, description: 'Primary phone number.', extraction_hint: 'Capture the main phone number.' },
        { id: 'location', label: 'Location', type: 'address', required: false, description: 'Location or city/state.', extraction_hint: 'Use the location line if shown.' },
        { id: 'headline', label: 'Headline', type: 'text', required: false, description: 'Professional summary headline or role.', extraction_hint: 'Capture the job-title-like summary near the name.' },
        { id: 'summary', label: 'Professional Summary', type: 'text', required: false, description: 'Narrative summary statement.', extraction_hint: 'Use the top summary/profile section if present.' },
        { id: 'skills', label: 'Skills', type: 'list', required: false, description: 'Combined skills list.', extraction_hint: 'Combine named tools, technologies, and skills into a concise list.' },
      ],
      groups: [
        {
          id: 'experience',
          label: 'Experience',
          repeat: true,
          description: 'Work experience entries.',
          key_hint: 'Company or role',
          fields: [
            { id: 'role', label: 'Role', type: 'text', required: true, description: 'Job title or role.', extraction_hint: 'Use the role title for the experience entry.' },
            { id: 'company', label: 'Company', type: 'text', required: false, description: 'Employer or organization.', extraction_hint: 'Use the employer or organization name.' },
            { id: 'location', label: 'Location', type: 'address', required: false, description: 'Entry-specific location.', extraction_hint: 'Use the location shown for the role if present.' },
            { id: 'start_date', label: 'Start Date', type: 'date', required: false, description: 'Role start date.', extraction_hint: 'Capture the start date or month/year.' },
            { id: 'end_date', label: 'End Date', type: 'date', required: false, description: 'Role end date or present marker.', extraction_hint: 'Capture the end date or Present marker.' },
            { id: 'description', label: 'Description', type: 'text', required: false, description: 'Concise summary of responsibilities or achievements.', extraction_hint: 'Combine the main bullets into a concise description.' },
          ],
          subgroups: [],
        },
        {
          id: 'education',
          label: 'Education',
          repeat: true,
          description: 'Education entries.',
          key_hint: 'Institution',
          fields: [
            { id: 'institution', label: 'Institution', type: 'text', required: true, description: 'School or university name.', extraction_hint: 'Use the institution name for the education entry.' },
            { id: 'degree', label: 'Degree', type: 'text', required: false, description: 'Degree or program.', extraction_hint: 'Capture the degree or academic program.' },
            { id: 'field_of_study', label: 'Field Of Study', type: 'text', required: false, description: 'Major or field of study.', extraction_hint: 'Use the stated major, concentration, or field.' },
            { id: 'graduation_date', label: 'Graduation Date', type: 'date', required: false, description: 'Graduation or expected graduation date.', extraction_hint: 'Capture the graduation date or expected graduation.' },
            { id: 'gpa', label: 'GPA', type: 'number', required: false, description: 'GPA if present.', extraction_hint: 'Capture GPA when clearly stated.' },
          ],
          subgroups: [],
        },
        {
          id: 'projects',
          label: 'Projects',
          repeat: true,
          description: 'Projects listed on the resume.',
          key_hint: 'Project name',
          fields: [
            { id: 'project_name', label: 'Project Name', type: 'text', required: true, description: 'Project title.', extraction_hint: 'Use the project or portfolio entry title.' },
            { id: 'description', label: 'Description', type: 'text', required: false, description: 'Project description.', extraction_hint: 'Summarize the key bullets for the project.' },
            { id: 'technologies', label: 'Technologies', type: 'list', required: false, description: 'Technologies used in the project.', extraction_hint: 'Capture named tools, frameworks, or languages tied to the project.' },
          ],
          subgroups: [],
        },
      ],
      warnings: [],
    },
  },
  {
    id: 'contract',
    label: 'Contract / Agreement',
    description: 'Agreement metadata, parties, dates, financial terms, and major clauses.',
    recommended_for: ['contract', 'agreement', 'msa', 'nda', 'sow'],
    spec: {
      document_type: 'Contract',
      title: 'Contract Extraction',
      detail_level: 'standard',
      summary: 'Extract core agreement metadata, parties, key dates, and major clause summaries.',
      fields: [
        { id: 'agreement_title', label: 'Agreement Title', type: 'text', required: true, description: 'Title of the contract or agreement.', extraction_hint: 'Use the document title or agreement heading.' },
        { id: 'effective_date', label: 'Effective Date', type: 'date', required: false, description: 'Date the agreement becomes effective.', extraction_hint: 'Look for effective date or commencement date.' },
        { id: 'execution_date', label: 'Execution Date', type: 'date', required: false, description: 'Date the agreement was signed or executed.', extraction_hint: 'Capture the execution or signature date if present.' },
        { id: 'party_one', label: 'Party One', type: 'text', required: false, description: 'First named party.', extraction_hint: 'Use the first legal party named in the opening paragraph.' },
        { id: 'party_two', label: 'Party Two', type: 'text', required: false, description: 'Second named party.', extraction_hint: 'Use the second legal party named in the opening paragraph.' },
        { id: 'term_length', label: 'Term Length', type: 'text', required: false, description: 'Length of the agreement term.', extraction_hint: 'Capture the stated duration or term description.' },
        { id: 'renewal_terms', label: 'Renewal Terms', type: 'text', required: false, description: 'Renewal conditions.', extraction_hint: 'Summarize auto-renewal or renewal language if present.' },
        { id: 'payment_terms', label: 'Payment Terms', type: 'text', required: false, description: 'High-level payment obligations.', extraction_hint: 'Capture the payment terms clause if clearly stated.' },
        { id: 'governing_law', label: 'Governing Law', type: 'text', required: false, description: 'Governing law jurisdiction.', extraction_hint: 'Use the governing law clause if present.' },
      ],
      groups: [
        {
          id: 'clauses',
          label: 'Major Clauses',
          repeat: true,
          description: 'Major sections or clauses worth summarizing.',
          key_hint: 'Clause heading',
          fields: [
            { id: 'clause_title', label: 'Clause Title', type: 'text', required: true, description: 'Clause or section heading.', extraction_hint: 'Use the clause heading or section title.' },
            { id: 'clause_summary', label: 'Clause Summary', type: 'text', required: false, description: 'Short summary of the clause.', extraction_hint: 'Summarize the clause in one or two concise sentences.' },
          ],
          subgroups: [],
        },
      ],
      warnings: [],
    },
  },
];

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function listPredefinedSchemas() {
  return PREDEFINED_SCHEMAS.map(schema => ({
    id: schema.id,
    label: schema.label,
    description: schema.description,
    recommended_for: schema.recommended_for,
  }));
}

function getPredefinedSchemaById(schemaId) {
  const match = PREDEFINED_SCHEMAS.find(schema => schema.id === schemaId);
  return match ? clone(match) : null;
}

module.exports = {
  getPredefinedSchemaById,
  listPredefinedSchemas,
};
